---
- hosts: all
  vars:
    current_user: "{{ ansible_user_id }}"
    new_shell: "{{ '/bin/zsh' }}"
    packages:
      - curl
      - git
      - vim
      - zsh
    git_repos:
      - { repo: 'https://github.com/MrXcitement/dot-git.git',
          dest: '~/github/mrxcitement/dot-git',
          version: main }
      - { repo: 'https://github.com/mrxcitement/dot-vim.git',
          dest: '~/github/mrxcitement/dot-vim',
          version: master }
      - { repo: 'https://github.com/mrxcitement/dot-zsh.git',
          dest: '~/github/mrxcitement/dot-zsh',
          version: master }
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Verify Packages
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items: "{{ packages }}"

    - name: Get the status of the file
      stat:
        path: '{{ item.dest }}'
      register: status
      with_items: "{{ git_repos }}"

    - name: Assert the status of the file is correct
      assert:
        that: '{{ item.stat.exists }}'
      with_items: '{{ status.results }}'

    - name: Get the current users passwd entry
      getent:
        database: passwd
        key: "{{ current_user }}"

    - debug:
        var: "getent_passwd.{{ current_user }}"

    - name: Assert the current user has the correct shell
      assert:
        that: '"{{ new_shell }}" in getent_passwd.{{ current_user }}'

