---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian10-ansible:latest
    # pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      # use platform name
      instance:
        ansible_user: ansible
verifier:
  name: ansible
